// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AutoruTestSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void correctEmailSignIn() {
    driver.get("https://auto.ru/");
    driver.manage().window().setSize(new Dimension(1256, 791));
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div/div/div[6]/a/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/form/div/div[2]/span/label/div/span/div[2]/input")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/form/div/div[2]/span/label/div/span/div[2]/input")).sendKeys("olibabamimedovich@gmail.com");
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/form/div/div[2]/span/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/form/div/div[3]/div[2]/label/div/span/div[2]/input")).click();
  }
  @Test
  public void incorrectEmailCodeSignIn() {
    driver.get("https://auto.ru/");
    driver.manage().window().setSize(new Dimension(1256, 791));
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div/div/div[6]/a/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/form/div/div[2]/span/label/div/span/div[2]/input")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/form/div/div[2]/span/label/div/span/div[2]/input")).sendKeys("olibabamimedovich@gmail.com");
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/form/div/div[2]/span/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/form/div/div[3]/div[2]/label/div/span/div[2]/input")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/form/div/div[3]/div[2]/label/div/span/div[2]/input")).sendKeys("342353");
  }
  @Test
  public void yandexSignIn() {
    driver.get("https://auto.ru/");
    driver.manage().window().setSize(new Dimension(1256, 791));
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div/div/div[6]/a/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/form/div/div[2]/div[3]/a/span/span/span[2]")).click();
    driver.findElement(By.xpath("//div[@id=\'root\']/div/div[2]/div[2]/div/div/div[2]/div[3]/div/div/div/ul/li/div/a")).click();
  }
  @Test
  public void placeForSale() {
    driver.get("https://auto.ru/");
    driver.manage().window().setSize(new Dimension(1256, 791));
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div/div/div[6]/a/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'tech.mark\']/ul/li[311]/a/div/img")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'tech.model\']/div/div[2]/a[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'tech.year\']/div/span")).click();
    driver.findElement(By.xpath("//div[@id=\'tech.body_type\']/div[2]")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'tech.engine_type\']/div/span/button/span/div"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'tech.engine_type\']/div/span/button/span/div")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".IconSvg_all-wheel-drive")).click();
    driver.findElement(By.xpath("//span[@id=\'tech.tech_param\']/label[2]/span/input")).click();
    {
      WebElement element = driver.findElement(By.xpath("//span[@id=\'tech.tech_param\']/label[2]/span/input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,274)");
    driver.findElement(By.xpath("//div[@id=\'tech.color\']/div")).click();
    driver.findElement(By.xpath("//div[@id=\'mileage\']/div[2]/div/label/div/span/div[2]/input")).click();
    driver.findElement(By.xpath("//div[@id=\'mileage\']/div[2]/div/label/div/span/div[2]/input")).sendKeys("1 003");
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'photos.without_photos\']/label/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'pts.pts_status\']/div[2]/span/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'pts.owners_number\']/div[2]/span/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'pts.purchase_date\']/div[2]/div/button/span")).click();
    driver.findElement(By.xpath("//body/div[3]/div/div/div")).click();
    driver.findElement(By.xpath("//div[@id=\'pts.purchase_date\']/div[2]/div[2]/button/span/span")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'pts.purchase_date\']/div[2]/div[2]/button/span/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//body/div[4]/div/div/div")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span/span")).click();
    js.executeScript("window.scrollTo(0,1916)");
    driver.findElement(By.xpath("//div[@id=\'description.description\']/div[2]/div/textarea")).click();
    driver.findElement(By.xpath("//div[@id=\'description.description\']/div[3]/div")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span")).click();
    js.executeScript("window.scrollTo(0,2390)");
    driver.findElement(By.xpath("//div[@id=\'complectation.complectation\']/div/span/button/span/span")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'complectation.complectation\']/div/span/button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'price.price\']/span/label/div/span/div/input")).click();
    driver.findElement(By.xpath("//div[@id=\'price.price\']/span/label/div/span/div/input")).sendKeys("1 000 000");
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,4815)");
    driver.findElement(By.xpath("//div[@id=\'section-sts\']/div[2]/div/div/label/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'sts.vin\']/label/div/span/div[2]/input")).click();
    driver.findElement(By.xpath("//div[@id=\'sts.vin\']/label/div/span/div[2]/input")).sendKeys("1KLBN52TWXM186109");
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'wizard-step-14\']/div/div[2]/div/div/div/div[2]/div/div[3]/div[2]/div[2]")).click();
    driver.findElement(By.xpath("//div[@id=\'do_not_publish\']/label/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'wizard-step-14\']/div/div[2]/div/button/span/span")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'wizard-step-14\']/div/div[2]/div/button/span/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
  @Test
  public void comparetwoautos() {
    driver.get("https://auto.ru/");
    driver.manage().window().setSize(new Dimension(1256, 791));
    js.executeScript("window.scrollTo(0,1127)");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//div[@id=\'LayoutIndex\']/div/div/div[4]/div/section/div/div/a/div/div/span/div/div/div[3]")).click();
    vars.put("win2335", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win2335").toString());
    driver.findElement(By.cssSelector(".IconSvg_more > use")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > .CardActions__action-MUIOE:nth-child(1)")).click();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//div[@id=\'LayoutIndex\']/div/div/div[4]/div/section/div/div[2]/a/div/div/span/div/div/div[3]")).click();
    vars.put("win5444", waitForWindow(2000));
    driver.switchTo().window(vars.get("win5444").toString());
    driver.findElement(By.cssSelector(".IconSvg_more > use")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > .CardActions__action-MUIOE:nth-child(1)")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div[2]/header/div/div/div[4]/a/div")).click();
    driver.findElement(By.xpath("//div[@id=\'LayoutIndex\']/div/div/label/span/span")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'LayoutIndex\']/div/div[2]/table/thead/tr/div/th[2]/div/a/img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'LayoutIndex\']/div/div[2]/table/thead/tr/div/th/div/div")).click();
    driver.findElement(By.cssSelector(".ComparisonHeader__item:nth-child(1) .CloseButton_color_black")).click();
  }
  @Test
  public void favoritestest() {
    driver.get("https://auto.ru/");
    driver.manage().window().setSize(new Dimension(1256, 791));
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div[2]/nav/ul/li[3]/a")).click();
    js.executeScript("window.scrollTo(0,170)");
    js.executeScript("window.scrollTo(0,596)");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//div[@id=\'listing-filters\']/div[9]/div[2]/div/div[2]/div/h3/a/div/div")).click();
    vars.put("win2094", waitForWindow(2000));
    driver.switchTo().window(vars.get("win2094").toString());
    driver.findElement(By.cssSelector(".CardActions__favoriteIcon-sfGVO")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div[2]/div[5]/div/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div[2]/header/div/div/div[4]/div[2]/div[2]/div/div/div/h3/a/div")).click();
    driver.findElement(By.cssSelector(".CardActions__favoriteIcon-sfGVO")).click();
  }
  @Test
  public void findCar() {
    driver.get("https://auto.ru/sankt-peterburg/cars/vaz/all/");
    driver.manage().window().setSize(new Dimension(1256, 791));
    {
      WebElement element = driver.findElement(By.cssSelector(".Select_checked .Button__text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//input[@name=\'price_to\']")).click();
    driver.findElement(By.name("price_to")).sendKeys("100 000");
    driver.findElement(By.xpath("//input[@name=\'km_age_to\']")).click();
    driver.findElement(By.name("km_age_to")).sendKeys("1 000 000");
    driver.findElement(By.xpath("//div[@id=\'listing-filters\']/div[2]/div[3]/div[3]/button/span/span")).click();
    js.executeScript("window.scrollTo(0,562)");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//div[@id=\'listing-filters\']/div[8]/div[2]/div/div/a/div/div/div[3]")).click();
    vars.put("win1884", waitForWindow(2000));
    driver.switchTo().window(vars.get("win1884").toString());
  }
  @Test
  public void reviewtest() {
    driver.get("https://auto.ru/sankt-peterburg/motorcycle/all/");
    driver.manage().window().setSize(new Dimension(1256, 791));
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div[2]/div[3]/div/div/div/div/a")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//div[@id=\'reviewsPageListing\']/div[4]/div/div[3]/a")).click();
    vars.put("win284", waitForWindow(2000));
    driver.switchTo().window(vars.get("win284").toString());
    js.executeScript("window.scrollTo(0,1774)");
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div[3]/div/div[2]/div[2]/div/span[2]/label/button/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div[3]/div/div[2]/div[2]/div/span[2]/label[2]/button/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div[3]/div/div[2]/div[2]/div/span[2]/label/button/span")).click();
    js.executeScript("window.scrollTo(0,2355)");
    js.executeScript("window.scrollTo(0,2696)");
    driver.findElement(By.xpath("//div[@id=\'reviewComments\']/div/div/div/div[2]/div/div/div/textarea")).click();
    driver.findElement(By.xpath("//div[@id=\'reviewComments\']/div/div/div/div[2]/div/div/div/textarea")).sendKeys("Мотоцикл бомба честно говоря!");
    driver.findElement(By.cssSelector(".IconSvg_send > use")).click();
  }
  @Test
  public void selectAnotherCity() {
    driver.get("https://auto.ru/");
    driver.manage().window().setSize(new Dimension(1256, 791));
    driver.findElement(By.linkText("Нижний Новгород")).click();
    js.executeScript("window.scrollTo(0,612)");
    js.executeScript("window.scrollTo(0,1162)");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//div[@id=\'LayoutIndex\']/div/div/div[4]/div/section/div/div[6]/a/div/div/span/div/div/div[3]")).click();
    vars.put("win8691", waitForWindow(2000));
    driver.switchTo().window(vars.get("win8691").toString());
  }
  @Test
  public void tabschecktest() {
    driver.get("https://auto.ru/");
    driver.manage().window().setSize(new Dimension(1256, 791));
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div[2]/nav/ul/li/a")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div[2]/header/div[2]/nav/ul/li[2]/a")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div[2]/header/div[2]/nav/ul/li[3]/a")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div[2]/header/div[2]/nav/ul/li[4]/a")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div[2]/nav/ul/li[5]/a")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div[2]/nav/ul/li[6]/a")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div[2]/nav/ul/li[7]/a")).click();
    driver.findElement(By.xpath("//button[@id=\'goToAutoRu\']/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div[2]/nav/ul/li[8]/a")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div[2]/nav/ul/li[9]/a")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div[2]/nav/ul/li[10]/a")).click();
  }
}
