// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class IncorrectEmailCodeSignInTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void incorrectEmailCodeSignIn() {
    driver.get("https://auto.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div/div/div[6]/a/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/form/div/div[2]/span/label/div/span/div[2]/input")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/form/div/div[2]/span/label/div/span/div[2]/input")).sendKeys("olibabamimedovich@gmail.com");
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/form/div/div[2]/span/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/form/div/div[3]/div[2]/label/div/span/div[2]/input")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/form/div/div[3]/div[2]/label/div/span/div[2]/input")).sendKeys("342353");
  }
}
