// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PlaceForSaleTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void placeForSale() {
    driver.get("https://auto.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div/div/div[6]/a/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'tech.mark\']/ul/li[311]/a/div/img")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'tech.model\']/div/div[2]/a[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'tech.year\']/div/span")).click();
    driver.findElement(By.xpath("//div[@id=\'tech.body_type\']/div[2]")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'tech.engine_type\']/div/span/button/span/div"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'tech.engine_type\']/div/span/button/span/div")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".IconSvg_all-wheel-drive")).click();
    driver.findElement(By.xpath("//span[@id=\'tech.tech_param\']/label[2]/span/input")).click();
    {
      WebElement element = driver.findElement(By.xpath("//span[@id=\'tech.tech_param\']/label[2]/span/input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,274)");
    driver.findElement(By.xpath("//div[@id=\'tech.color\']/div")).click();
    driver.findElement(By.xpath("//div[@id=\'mileage\']/div[2]/div/label/div/span/div[2]/input")).click();
    driver.findElement(By.xpath("//div[@id=\'mileage\']/div[2]/div/label/div/span/div[2]/input")).sendKeys("1 003");
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'photos.without_photos\']/label/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'pts.pts_status\']/div[2]/span/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'pts.owners_number\']/div[2]/span/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'pts.purchase_date\']/div[2]/div/button/span")).click();
    driver.findElement(By.xpath("//body/div[3]/div/div/div")).click();
    driver.findElement(By.xpath("//div[@id=\'pts.purchase_date\']/div[2]/div[2]/button/span/span")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'pts.purchase_date\']/div[2]/div[2]/button/span/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//body/div[4]/div/div/div")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span/span")).click();
    js.executeScript("window.scrollTo(0,1916)");
    driver.findElement(By.xpath("//div[@id=\'description.description\']/div[2]/div/textarea")).click();
    driver.findElement(By.xpath("//div[@id=\'description.description\']/div[3]/div")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span")).click();
    js.executeScript("window.scrollTo(0,2390)");
    driver.findElement(By.xpath("//div[@id=\'complectation.complectation\']/div/span/button/span/span")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'complectation.complectation\']/div/span/button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'price.price\']/span/label/div/span/div/input")).click();
    driver.findElement(By.xpath("//div[@id=\'price.price\']/span/label/div/span/div/input")).sendKeys("1 000 000");
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,4815)");
    driver.findElement(By.xpath("//div[@id=\'section-sts\']/div[2]/div/div/label/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'sts.vin\']/label/div/span/div[2]/input")).click();
    driver.findElement(By.xpath("//div[@id=\'sts.vin\']/label/div/span/div[2]/input")).sendKeys("1KLBN52TWXM186109");
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/div/div/form/div/div/div/div/div[2]/div[11]/div/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'wizard-step-14\']/div/div[2]/div/div/div/div[2]/div/div[3]/div[2]/div[2]")).click();
    driver.findElement(By.xpath("//div[@id=\'do_not_publish\']/label/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'wizard-step-14\']/div/div[2]/div/button/span/span")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'wizard-step-14\']/div/div[2]/div/button/span/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
